services:
  - type: web
    name: laravel-app
    env: php
    buildCommand: |
      curl -sS https://getcomposer.org/installer | php
      php composer.phar install
    startCommand: "php -S 0.0.0.0:10000 -t public"
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: # You will generate this after the first deploy


